import { parseSSEStream, type SSEEvent } from "./sse-parser";

// --- Chat ---

interface SendMessageParams {
  conversationId?: string;
  content: string;
  model?: string;
  signal?: AbortSignal;
}

export async function* sendMessage(
  params: SendMessageParams
): AsyncGenerator<SSEEvent> {
  const { signal, ...body } = params;
  const response = await fetch("/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal,
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: "Request failed" }));
    yield { type: "error", error: err.error || `HTTP ${response.status}` };
    return;
  }

  yield* parseSSEStream(response);
}

// --- Models ---

export async function fetchModels() {
  const res = await fetch("/api/models");
  if (!res.ok) return [];
  const data = await res.json();
  return data.models as Array<{ id: string; name: string; provider: string }>;
}

// --- Conversations ---

export interface ConversationSummary {
  id: string;
  title: string | null;
  model: string;
  updatedAt: string;
  _count: { messages: number };
}

export interface ConversationDetail {
  id: string;
  title: string | null;
  model: string;
  messages: Array<{
    id: string;
    role: string;
    content: string;
    model: string | null;
    createdAt: string;
  }>;
}

export async function fetchConversations(search?: string): Promise<ConversationSummary[]> {
  const params = new URLSearchParams();
  if (search) params.set("search", search);
  const res = await fetch(`/api/conversations?${params}`);
  if (!res.ok) return [];
  const data = await res.json();
  return data.conversations;
}

export async function fetchConversation(id: string): Promise<ConversationDetail | null> {
  const res = await fetch(`/api/conversations/${id}`);
  if (!res.ok) return null;
  return res.json();
}

export async function createConversation(model?: string) {
  const res = await fetch("/api/conversations", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ model }),
  });
  return res.json();
}

export async function updateConversation(id: string, data: { title?: string; isArchived?: boolean }) {
  const res = await fetch(`/api/conversations/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  return res.json();
}

export async function deleteConversation(id: string) {
  await fetch(`/api/conversations/${id}`, { method: "DELETE" });
}

export async function generateTitle(conversationId: string): Promise<string> {
  const res = await fetch(`/api/conversations/${conversationId}/title`, { method: "POST" });
  const data = await res.json();
  return data.title || "新对话";
}

// --- Notes ---

export interface NoteSummary {
  id: string;
  title: string;
  summary: string | null;
  updatedAt: string;
  conversation: { id: string; title: string | null } | null;
  tags: Array<{ tag: { id: string; name: string; color: string | null } }>;
}

export async function fetchNotes(params?: { tagId?: string; search?: string }): Promise<NoteSummary[]> {
  const sp = new URLSearchParams();
  if (params?.tagId) sp.set("tagId", params.tagId);
  if (params?.search) sp.set("search", params.search);
  const res = await fetch(`/api/notes?${sp}`);
  if (!res.ok) return [];
  const data = await res.json();
  return data.notes;
}

export async function fetchNote(id: string) {
  const res = await fetch(`/api/notes/${id}`);
  if (!res.ok) return null;
  return res.json();
}

export async function exportConversationToNote(conversationId: string) {
  const res = await fetch("/api/notes/auto-export", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ conversationId }),
  });
  return res.json();
}

export async function deleteNote(id: string) {
  await fetch(`/api/notes/${id}`, { method: "DELETE" });
}

// --- Tags ---

export interface TagWithCount {
  id: string;
  name: string;
  color: string | null;
  isAutoGenerated: boolean;
  _count: { notes: number; conversations: number };
}

export async function fetchTags(): Promise<TagWithCount[]> {
  const res = await fetch("/api/tags");
  if (!res.ok) return [];
  const data = await res.json();
  return data.tags;
}

export async function fetchTagDetail(id: string) {
  const res = await fetch(`/api/tags/${id}`);
  if (!res.ok) return null;
  return res.json();
}

export async function createTag(name: string, color?: string) {
  const res = await fetch("/api/tags", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, color }),
  });
  return res.json();
}

export async function deleteTag(id: string) {
  await fetch(`/api/tags/${id}`, { method: "DELETE" });
}

// --- Settings ---

export interface CustomProviderData {
  id: string;
  name: string;
  baseUrl: string;
  apiKey: string;
  modelId: string;
  modelName: string;
  apiFormat: string;
}

export interface UserSettingsData {
  openaiApiKey: string;
  openaiBaseUrl: string;
  anthropicApiKey: string;
  ollamaBaseUrl: string;
  customProviders: CustomProviderData[];
  testedProviders: string[];
  hasOpenaiKey: boolean;
  hasAnthropicKey: boolean;
}

export async function fetchSettings(): Promise<UserSettingsData> {
  const res = await fetch("/api/settings");
  if (!res.ok) {
    return { openaiApiKey: "", openaiBaseUrl: "", anthropicApiKey: "", ollamaBaseUrl: "", customProviders: [], testedProviders: [], hasOpenaiKey: false, hasAnthropicKey: false };
  }
  return res.json();
}

export async function saveSettings(data: Record<string, unknown>) {
  const res = await fetch("/api/settings", {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  return res.json();
}
