import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUserId } from "@/lib/get-user";
import { modelRouter } from "@/lib/llm/model-router";

export async function POST(req: NextRequest) {
  const userId = await getCurrentUserId();
  const body = await req.json();
  const { conversationId } = body;

  if (!conversationId) {
    return Response.json({ error: "conversationId is required" }, { status: 400 });
  }

  const conversation = await prisma.conversation.findUnique({
    where: { id: conversationId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });

  if (!conversation) {
    return Response.json({ error: "Conversation not found" }, { status: 404 });
  }

  // Build note content from conversation
  const noteContent = conversation.messages
    .map((m) => {
      const role = m.role === "USER" ? "**用户**" : "**AI**";
      return `${role}:\n\n${m.content}`;
    })
    .join("\n\n---\n\n");

  // Generate summary and tags via LLM
  let summary = "";
  let suggestedTags: string[] = [];
  const title = conversation.title || "导出笔记";

  try {
    const gen = modelRouter.chat({
      model: conversation.model || "gpt-4o",
      messages: [
        {
          role: "user",
          content: `Analyze this conversation and provide:
1. A brief summary (2-3 sentences, in the conversation's language)
2. 3-5 relevant tags (single words or short phrases, in the conversation's language)

Format your response as JSON: {"summary": "...", "tags": ["tag1", "tag2", ...]}

Conversation:
${noteContent.slice(0, 3000)}`,
        },
      ],
      temperature: 0.3,
      maxTokens: 300,
    });

    let result = "";
    for await (const chunk of gen) {
      if (chunk.type === "token" && chunk.content) {
        result += chunk.content;
      }
    }

    // Parse JSON from LLM response
    const jsonMatch = result.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      summary = parsed.summary || "";
      suggestedTags = (parsed.tags || []).slice(0, 5);
    }
  } catch {
    // Fallback - no summary or tags
  }

  // Create or find tags
  const tagRecords = await Promise.all(
    suggestedTags.map(async (name: string) => {
      const trimmed = name.trim().toLowerCase();
      if (!trimmed) return null;
      return prisma.tag.upsert({
        where: { name: trimmed },
        create: { name: trimmed, isAutoGenerated: true },
        update: {},
      });
    })
  );

  const validTagIds = tagRecords.filter(Boolean).map((t) => t!.id);

  // Create the note
  const note = await prisma.note.create({
    data: {
      title,
      content: noteContent,
      summary,
      conversationId,
      userId,
      tags: {
        create: validTagIds.map((tagId) => ({ tagId })),
      },
    },
    include: {
      tags: { include: { tag: true } },
    },
  });

  // Also tag the conversation
  for (const tagId of validTagIds) {
    await prisma.tagOnConversation.upsert({
      where: { conversationId_tagId: { conversationId, tagId } },
      create: { conversationId, tagId },
      update: {},
    });
  }

  return Response.json(note, { status: 201 });
}
