import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUserId } from "@/lib/get-user";
import { chat } from "@/lib/llm/model-router";
import { getUserApiKeys } from "@/lib/llm/get-api-keys";

export async function POST(req: NextRequest) {
  const userId = await getCurrentUserId();
  const keys = await getUserApiKeys();
  const body = await req.json();
  const { conversationId } = body;

  if (!conversationId) {
    return Response.json({ error: "conversationId is required" }, { status: 400 });
  }

  const conversation = await prisma.conversation.findUnique({
    where: { id: conversationId },
    include: {
      messages: { orderBy: { createdAt: "asc" } },
    },
  });

  if (!conversation) {
    return Response.json({ error: "Conversation not found" }, { status: 404 });
  }

  // Build the raw dialogue for LLM analysis
  const rawDialogue = conversation.messages
    .map((m) => {
      const role = m.role === "USER" ? "用户" : "AI";
      return `${role}: ${m.content}`;
    })
    .join("\n\n");

  // Generate title, summary, key points, and tags via LLM
  let title = conversation.title || "学习笔记";
  let summary = "";
  let keyPoints: string[] = [];
  let suggestedTags: string[] = [];

  const model = conversation.model || "gpt-4o";

  try {
    const gen = chat({
      model,
      messages: [
        {
          role: "user",
          content: `你是一个学习笔记助手。请分析以下对话，生成结构化的学习笔记元数据。

要求：
1. title: 一个简洁准确的笔记标题（不超过20字）
2. summary: 2-3句话的核心摘要，概括对话的主要内容和结论
3. keyPoints: 3-5个关键知识点，每个用一句话概括
4. tags: 3-5个分类标签（短词）

请严格使用JSON格式返回：
{"title": "...", "summary": "...", "keyPoints": ["...", "..."], "tags": ["...", "..."]}

对话内容：
${rawDialogue.slice(0, 4000)}`,
        },
      ],
      temperature: 0.3,
      maxTokens: 500,
    }, keys);

    let result = "";
    for await (const chunk of gen) {
      if (chunk.type === "token" && chunk.content) {
        result += chunk.content;
      }
    }

    const jsonMatch = result.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      title = parsed.title || title;
      summary = parsed.summary || "";
      keyPoints = (parsed.keyPoints || []).slice(0, 5);
      suggestedTags = (parsed.tags || []).slice(0, 5);
    }
  } catch {
    // Fallback - use conversation title
  }

  // Build structured note content
  const noteContent = buildNoteContent({
    title,
    summary,
    keyPoints,
    messages: conversation.messages,
  });

  // Create or find tags
  const tagRecords = await Promise.all(
    suggestedTags.map(async (name: string) => {
      const trimmed = name.trim().toLowerCase();
      if (!trimmed) return null;
      return prisma.tag.upsert({
        where: { name: trimmed },
        create: { name: trimmed, isAutoGenerated: true },
        update: {},
      });
    })
  );

  const validTagIds = tagRecords.filter(Boolean).map((t) => t!.id);

  // Create the note
  const note = await prisma.note.create({
    data: {
      title,
      content: noteContent,
      summary,
      conversationId,
      userId,
      tags: {
        create: validTagIds.map((tagId) => ({ tagId })),
      },
    },
    include: {
      tags: { include: { tag: true } },
    },
  });

  // Also tag the conversation
  for (const tagId of validTagIds) {
    await prisma.tagOnConversation.upsert({
      where: { conversationId_tagId: { conversationId, tagId } },
      create: { conversationId, tagId },
      update: {},
    });
  }

  return Response.json(note, { status: 201 });
}

function buildNoteContent({
  title,
  summary,
  keyPoints,
  messages,
}: {
  title: string;
  summary: string;
  keyPoints: string[];
  messages: Array<{ role: string; content: string }>;
}) {
  const sections: string[] = [];

  // Header
  sections.push(`# ${title}\n`);

  // Summary
  if (summary) {
    sections.push(`## 摘要\n\n${summary}\n`);
  }

  // Key points
  if (keyPoints.length > 0) {
    sections.push(`## 关键知识点\n\n${keyPoints.map((p) => `- ${p}`).join("\n")}\n`);
  }

  // Dialogue content - formatted as Q&A pairs
  sections.push(`## 对话详情\n`);

  let currentQ = "";
  for (const m of messages) {
    if (m.role === "USER") {
      currentQ = m.content;
    } else if (m.role === "ASSISTANT") {
      if (currentQ) {
        sections.push(`### Q: ${currentQ.length > 80 ? currentQ.slice(0, 80) + "..." : currentQ}\n`);
        sections.push(m.content + "\n");
        currentQ = "";
      } else {
        sections.push(m.content + "\n");
      }
    }
  }

  return sections.join("\n");
}
